[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gripper"
requires-python = ">=3.11"
dynamic = ["version"]
dependencies = [
    "requests",
    "pydantic",
    "beautifulsoup4>=4.15.0",
    "rich>=15.0.0",
    "pydantic-settings>=2.15.0",
]

[project.scripts]
gripper = "gripper.main:main"

[dependency-groups]
test = ["pytest", "coverage"]
